USE SUPPLYCHAINDB;

-- ----------------------------------------------------------------------------------------------------------------
DELIMITER //
-- STORED PROCEDURE FOR JOIN OF SUPPLIER, EMPLOYEE AND APPROVAL_DETAILS
CREATE PROCEDURE APPROVAL_WITH_EMPLOYEE_AND_SUPPLIER(
IN APPROVAL_ID INT,
    OUT DETAILS INT)
BEGIN 
	SELECT 
    E.APPROVAL_ID,
    E.PART_ID,
    E.SUBMIT_DATE,
    E.COST,
    E.APP_EMP_ID AS EMP_ID,
    E.EMP_NAME,
    S.SUPPLIER_ID,
    S.SUPPLIER_NAME,
    S.STATUS,
    S.STATUS_DATE
    FROM APPROVAL_WITH_EMPLOYEE E
    LEFT OUTER JOIN SupplyChainDB.APPROVAL_WITH_SUPPLIER S 
        ON S.APPROVAL_ID = E.APPROVAL_ID
	WHERE E.APPROVAL_ID = APPROVAL_ID;
END //
-- EXECUTING STORED PROCEDURE
CALL APPROVAL_WITH_EMPLOYEE_AND_SUPPLIER(4006, @DETAILS);
DELIMITER ;

-- ----------------------------------------------------------------------------------------------------------------

DELIMITER //
-- CHANCES OF SUPPLIER APPROVING THE DEMAND OF THE CUSTOMER
CREATE PROCEDURE APPROVAL_CHANCES_BY_SUPPLIER(
	IN SUPPLIER_ID INT,
    OUT CHANCES INT)
	BEGIN 
		SELECT * FROM EVALUATION_STATS_SUPPLIER;
		SELECT 
			S.SUPPLIER_ID, 
			S.SUPPLIER_NAME, 
			(SUM(APPROVED) / (SUM(APPROVED)+SUM(DENIED)+SUM(PENDING)))*100 AS APPROVAL_CHANCES 
		FROM SupplyChainDB.EVALUATION_STATS_SUPPLIER S
        WHERE S.SUPPLIER_ID = SUPPLIER_ID
			GROUP BY SUPPLIER_ID, SUPPLIER_NAME;
	END //
-- EXECUTING STORED PROCEDURE
CALL APPROVAL_CHANCES_BY_SUPPLIER(302, @CHANCES);
DELIMITER ;

-- ----------------------------------------------------------------------------------------------------------------

DELIMITER //
-- FOR CHECKING EVALUATION TIME 
CREATE PROCEDURE EMP_EVALUATION(
	IN EMP_ID INT,
    OUT EVALUATION INT)
BEGIN
	DECLARE EVALUATION INT;
    
	SELECT 
		E.APP_EMP_ID, E.AVG_EVALUATION_TIME 
	FROM 
		EVALUATION_STATS_EMPLOYEE E
	WHERE 
		E.APP_EMP_ID = EMP_ID;
    
END //
-- EXECUTING STORED PROCEDURE
CALL EMP_EVALUATION(123458, @EVALUATION);

DELIMITER ;

 -- ----------------------------------------------------------------------------------------------------------------
