DELIMITER //
-- STORED PROCEDURE FOR JOIN OF SUPPLIER, EMPLOYEE AND APPROVAL_DETAILS
CREATE PROCEDURE APPROVAL_WITH_EMPLOYEE_AND_SUPPLIER()
BEGIN 
	SELECT 
    E.APPROVAL_ID,
    E.PART_ID,
    E.SUBMIT_DATE,
    E.COST,
    E.APP_EMP_ID AS EMP_ID,
    E.EMP_NAME,
    S.SUPPLIER_ID,
    S.SUPPLIER_NAME,
    S.STATUS,
    S.STATUS_DATE
    FROM APPROVAL_WITH_EMPLOYEE E
    LEFT OUTER JOIN SupplyChainDB.APPROVAL_WITH_SUPPLIER S 
        ON S.APPROVAL_ID = E.APPROVAL_ID;
END //
-- EXECUTING STORED PROCEDURE
CALL APPROVAL_WITH_EMPLOYEE_AND_SUPPLIER();
DELIMITER ;

DELIMITER //
-- CHANCES OF SUPPLIER APPROVING THE DEMAND OF THE CUSTOMER
CREATE PROCEDURE APPROVAL_CHANCES_BY_SUPPLIER()
	BEGIN 
		SELECT * FROM EVALUATION_STATS_SUPPLIER;
		SELECT 
			SUPPLIER_ID, 
			SUPPLIER_NAME, 
			(SUM(APPROVED) / (SUM(APPROVED)+SUM(DENIED)+SUM(PENDING)))*100 AS APPROVAL_CHANCES 
		FROM SupplyChainDB.EVALUATION_STATS_SUPPLIER 
			GROUP BY SUPPLIER_ID, SUPPLIER_NAME;
	END //
-- EXECUTING STORED PROCEDURE
CALL APPROVAL_CHANCES_BY_SUPPLIER();
DELIMITER ;


DELIMITER //
-- FOR CHECKING EVALUATION TIME 
CREATE PROCEDURE EMP_EVALUATION(
	IN EMP_ID INT,
    OUT EVALUATION INT)
BEGIN
	DECLARE EVALUATION INT;
    
	SELECT 
		E.APP_EMP_ID, E.AVG_EVALUATION_TIME 
	FROM 
		EVALUATION_STATS_EMPLOYEE E
	WHERE 
		E.APP_EMP_ID = EMP_ID;
    
END //
-- EXECUTING STORED PROCEDURE
CALL EMP_EVALUATION(123458, @EVALUATION);

DELIMITER ;
 
-- FUNCTION TO GENERATE ADDRESS OF THE CUSTOMER
SELECT * FROM CUSTOMER;

ALTER TABLE CUSTOMER
ADD COLUMN
 CUST_ADDRESS2 VARCHAR(500) GENERATED ALWAYS AS (CONCAT(CUST_STREET,',', CUST_CITY,',',CUST_STATE,',', CUST_ZIP));
   
SELECT * FROM CUSTOMER;

 