-- CUSTOMER
-- SELECT ALL CUSTOMER
SELECT * FROM CUSTOMER;
-- SELECT CUSTOMER FROM A REGION
SELECT * FROM CUSTOMER C WHERE C.CUST_REGION = 'E'; 

-- PROGRAMS
-- SELECT ALL PROGRAMS
SELECT * FROM PROGRAMS;
-- SELECT ACTIVE PROGRAM
SELECT * FROM PROGRAMS WHERE PROG_STATUS IN ('OPEN','DELAYED');
-- SELECT BY STATUS
SELECT * FROM PROGRAMS WHERE PROG_STATUS = 'OPEN';
-- SELECT PROGRAM BY YEAR
SELECT * FROM PROGRAMS P WHERE 2016 BETWEEN YEAR(P.PROG_START) AND YEAR(P.PROG_END);
-- SELECT PROGRAM BY YEAR AND STATUS
SELECT * FROM PROGRAMS P WHERE 2016 BETWEEN YEAR(P.PROG_START) AND YEAR(P.PROG_END) AND PROG_STATUS = 'OPEN';

-- EMPLOYEE 
-- SELECT ALL EMPLOYEE
SELECT * FROM EMPLOYEE;
-- SLECT ACTIVE EMPLOYEE 
SELECT * FROM EMPLOYEE WHERE EMP_ENDDATE IS NULL AND EMP_HIREDATE <= NOW();
-- SELECT NOT ACTIVE EMPLOYEE
 SELECT * FROM EMPLOYEE WHERE EMP_ENDDATE IS NOT NULL;
 -- SELECT EMPLOYEE BY YEAR
 SELECT * FROM EMPLOYEE E WHERE 2014 BETWEEN YEAR(E.EMP_HIREDATE) AND YEAR(EMP_ENDDATE);
 
 -- PART
 -- SELECT ALL PARTS
 SELECT * FROM PART;
 -- SELECT PARTS BY STATUS
 SELECT * FROM PART WHERE STATUS = 'OPEN'; 
 SELECT * FROM PART WHERE STATUS = 'CLOSED'; 
 -- SELECT PARTS BY COMMODITY
  SELECT * FROM PART WHERE COMMODITY = 'FORGING'; 
-- SELECT COMMODITY AND STATUS
  SELECT * FROM PART WHERE COMMODITY = 'FORGING' AND STATUS = 'OPEN'; 
  SELECT * FROM PART WHERE COMMODITY = 'FORGING' AND STATUS = 'CLOSED'; 

-- SUPPLIER
-- SELECT ALL SUPPLIER
SELECT * FROM SUPPLIER;
-- SELECT SUPPLIER FROM PARTICULSR REGION
SELECT * FROM SUPPLIER WHERE SUPP_REGION = 'NE'; 

-- SUPPLIER CONTACT
-- SELECT ALL SUPPLIER CONTACT
SELECT * FROM SUPPLIER_CONTACT;
-- SELECT A PARTICULAR SUPPLIER'S PHONE AND EMAIL ADDRESS
 SELECT SUPP_EMP_NAME, SUPP_EMP_EMAIL, SUPP_EMP_PHONE FROM SUPPLIER_CONTACT WHERE REGEXP_LIKE(SUPP_EMP_NAME, 'EE');

-- PROGRAMS
-- SELECT ALL PROGRAMS
SELECT * FROM PROGRAMS;
SELECT * FROM PROGRAM_PART;
SELECT * FROM PART;
-- NUMBER OF PARTICULAR PART REQUIRED FOR A PROGRAM
SELECT PROG_ID, PART_ID, QTY_FACTOR FROM PROGRAM_PART WHERE PROG_ID = '101';
SELECT PROG_ID, PART_ID, QTY_FACTOR FROM PROGRAM_PART WHERE PROG_ID = '101' AND PART_ID = '50001';
-- TOTAL NUMBER OF PARTS IN A PROGRAM
SELECT PROG_ID, COUNT(*) AS NO_OF_PARTS FROM PROGRAM_PART WHERE PROG_ID = '101';
-- NUMBER OF PROGRAMS THAT NEED A PART WHOSE QUANTITY FACTOR IS GREATER THAN 1
SELECT * FROM PROGRAM_PART WHERE QTY_FACTOR > 1;

-- OUTGOING INVOICES
-- SELECT ALL OUTGOING INVOICES
SELECT * FROM OUTGOING_INVOICE;
-- SELECT NUMBER OF OUTGOING PARTS(QUANTITY) IN THE BATCH
SELECT * FROM OUTGOING_INVOICE WHERE OUT_INV_NO = '201901';
-- SELECT NUMBER OF OUTGOING PARTS FOR ALL BATCHES FOR A PPID
SELECT * FROM OUTGOING_INVOICE WHERE PROG_PART_ID = '60001';
-- SELECT NUMBER OF OUTGOING PARTS FOR A PPID FOR THE LATEST BATCH
SELECT * FROM OUTGOING_INVOICE WHERE OUT_INV_DATE = (SELECT MAX(OUT_INV_DATE) FROM OUTGOING_INVOICE WHERE PROG_PART_ID = '60001');
-- SELECT ALL OUTGOING INVOICE FOR A PARTICULAR YEAR
SELECT * FROM OUTGOING_INVOICE WHERE 
    EXTRACT(YEAR FROM OUT_INV_DATE) = '2016';
-- SELECT ALL OUTGOING INVOICE FOR A PPID FOR A PARTICULAR YEAR
SELECT * FROM OUTGOING_INVOICE WHERE 
    EXTRACT(YEAR FROM OUT_INV_DATE) = '2016' AND PROG_PART_ID = '60004';
-- TOTAL QUANTITY DISPATCHED FOR A PARTICULAR PPID
SELECT PROG_PART_ID, SUM(QUANTITY) AS TOTAL_QTY_DISPATCHED FROM OUTGOING_INVOICE 
    WHERE PROG_PART_ID = '60001' GROUP BY PROG_PART_ID;
-- SELECT TOTAL NUMBER OF INVOICES IN A MONTH AND YEAR
SELECT * FROM OUTGOING_INVOICE WHERE 
    EXTRACT(MONTH FROM OUT_INV_DATE)= 02 AND EXTRACT(YEAR FROM OUT_INV_DATE)= 2016;

-- EMPLOYEE_PROGRAMS
-- SELECT ALL EMPLOYEE_PROGRAMS
SELECT * FROM EMPLOYEE_PROGRAM;
-- SELECT THE START AND END DATE OF AN EMPLOYEE FOR ALL PROGRAMS ASSOCIATED WITH HIM/HER
SELECT EMP_ID, PROG_ID, START_DATE, END_DATE FROM EMPLOYEE_PROGRAM WHERE EMP_ID = '123456';
-- SELECT EMPLOYEE_ID OF A PROGRAM MANAGER
SELECT * FROM EMPLOYEE_PROGRAM WHERE DESIGNATION = 'PROGRAM MANAGER';
-- TOTAL NUMBER OF EMPLOYEE IN A PROGRAM
SELECT * FROM EMPLOYEE_PROGRAM WHERE PROG_ID = '101';
SELECT PROG_ID, COUNT(*) AS NO_OF_EMPLOYEE FROM EMPLOYEE_PROGRAM WHERE PROG_ID = '101' GROUP BY PROG_ID;
-- FINDING ALL ACTIVE EMPLOYEE PROGRAM AS OF TODAY 
SELECT * FROM EMPLOYEE_PROGRAM WHERE END_DATE >= NOW() OR END_DATE IS NULL;
-- FINDING EMPLOYEE WHO ARE NOT ASSOCIATED WITH ANY PROGRAM AS OF TODAY
SELECT * FROM EMPLOYEE_PROGRAM WHERE END_DATE < NOW();

-- APPROVAL_DETAILS
-- SELECT ALL APPROVAL_DETAILS
SELECT * FROM APPROVAL_DETAILS;
-- SELECT ALL APPROVAL DETAILS FOR A PARTICULAR PART_ID
SELECT * FROM APPROVAL_DETAILS WHERE PART_ID = '50003';
-- SELECT ALL PART APPROVAL DETAILS FOR A PARTICULAR SUPPLIER
SELECT * FROM APPROVAL_DETAILS WHERE SUPP_ID = '302';
-- SELECT ALL APPROVAL DETAILS FOR A PART FROM A PARTICULAR SUPPLIER
SELECT * FROM APPROVAL_DETAILS WHERE PART_ID = '50003' AND SUPP_ID = '301';
-- SELECT ALL APPROVAL DATE FOR A PART ID
SELECT PART_ID, APP_DATE FROM APPROVAL_DETAILS WHERE PART_ID = '50003';
-- SELECT ALL SQE FOR A SUPPLIER
SELECT SUPP_ID, SQE_REP FROM APPROVAL_DETAILS WHERE SUPP_ID = '301';
-- SELECT APPROVAL COST FOR A PART
SELECT PART_ID, APP_STATUS, APP_COST FROM APPROVAL_DETAILS WHERE PART_ID = '50003';
-- SELECT ALL APPROVED STATUS
SELECT * FROM APPROVAL_DETAILS WHERE APP_STATUS = 'APPROVED';
-- SELECT ALL PENDING STAUS
SELECT * FROM APPROVAL_DETAILS WHERE APP_STATUS = 'PENDING';
-- SELECT ALL APPROVAL IN A YEAR
SELECT * FROM APPROVAL_DETAILS WHERE YEAR(APP_DATE) = '2015';

-- PURCHASE_ORDER
-- SELECT ALL PURCHASE_ORDER
SELECT * FROM PURCHASE_ORDER;
-- SELECT A PARTICULAR PURCHASE_ORDER DATE FOR APPROVAL_ID
SELECT PART_APPR_ID, PO_DATE FROM PURCHASE_ORDER WHERE PART_APPR_ID = '4006';
-- SELECT ITEM_QUANTITY FOR A PARTICULAR PART_APPR_ID
SELECT PART_APPR_ID, ITEM_QTY FROM PURCHASE_ORDER WHERE PART_APPR_ID = '4006';

SELECT * FROM APPROVAL_DETAILS;
SELECT * FROM PART;
SELECT * FROM PROGRAM_PART;
SELECT * FROM PROGRAMS;

SELECT * FROM SUPPLIER;
SELECT * FROM SUPPLIER_CONTACT;
SELECT * FROM EMPLOYEE;
SELECT * FROM EMPLOYEE_PROGRAM;
SELECT * FROM PROGRAM_PART WHERE PART_ID = (SELECT PART_ID FROM APPROVAL_DETAILS WHERE APP_STATUS = 'PENDING'); -- 50004



SELECT P.CUST_ID, P.PROG_ID FROM PROGRAMS P WHERE P.PROG_ID IN (SELECT PP.PROG_ID FROM PROGRAM_PART PP WHERE PP.PART_ID = 
(SELECT PART_ID FROM APPROVAL_DETAILS WHERE APP_STATUS = 'PENDING'));

SELECT P.CUST_ID FROM PROGRAMS P 
RIGHT JOIN PROGRAM_PART PP ON P.PROG_ID IN (SELECT PROG_ID FROM PROGRAM_PART WHERE PART_ID = 
(SELECT PART_ID FROM APPROVAL_DETAILS WHERE APP_STATUS = 'PENDING'));

SELECT P.CUST_ID FROM PROGRAMS P 
WHERE P.PROG_ID IN (SELECT PROG_ID FROM PROGRAM_PART WHERE PART_ID = 
(SELECT PART_ID FROM APPROVAL_DETAILS WHERE APP_STATUS = 'PENDING'));

select *, (SELECT C.CUST_NAME FROM CUSTOMER C WHERE C.CUST_ID IN
(	
	SELECT P.CUST_ID FROM PROGRAMS P 
	WHERE P.PROG_ID IN (SELECT PROG_ID FROM PROGRAM_PART WHERE PART_ID = 
	(SELECT PART_ID FROM APPROVAL_DETAILS WHERE APP_STATUS = 'PENDING'))
)) from APPROVAL_DETAILS AP
where AP.APP_STATUS = 'PENDING';
 -- JOIN EMPLOYEE_PROGRAM EP ON EP.PROG_ID = P.PROG_ID WHERE EP.DESIGNATION = 'PROGRAM MANAGER';
 
 



CREATE VIEW PENDING_PART_DETAILS AS
SELECT C.CUST_NAME, P.PROG_ID, P.PROG_NAME, AP.PART_ID FROM CUSTOMER C INNER JOIN PROGRAMS P ON C.CUST_ID IN
(SELECT P.CUST_ID FROM PROGRAMS P WHERE P.PROG_ID IN 
	(SELECT PROG_ID FROM PROGRAM_PART WHERE PART_ID = 
	 (SELECT PART_ID FROM APPROVAL_DETAILS WHERE APP_STATUS = 'PENDING')
	)
)
INNER JOIN APPROVAL_DETAILS AP ON AP.APP_STATUS = 'PENDING'
INNER JOIN EMPLOYEE_PROGRAM EP ON EP.PROG_ID = P.PROG_ID WHERE EP.DESIGNATION = 'PROGRAM MANAGER';




SELECT * FROM PENDING_PART_DETAILS;

SELECT C.CUST_NAME, P.PROG_ID, P.PROG_NAME, AP.PART_ID FROM CUSTOMER C INNER JOIN PROGRAMS P ON C.CUST_ID IN
(SELECT P.CUST_ID FROM PROGRAMS P WHERE P.PROG_ID IN (SELECT PP.PROG_ID FROM PROGRAM_PART PP WHERE PP.PART_ID = 
(SELECT AP.PART_ID FROM APPROVAL_DETAILS AP WHERE AP.APP_STATUS = 'PENDING')))
INNER JOIN APPROVAL_DETAILS AP ON AP.APP_STATUS = 'PENDING'
INNER JOIN EMPLOYEE_PROGRAM EP ON EP.PROG_ID = P.PROG_ID WHERE EP.DESIGNATION = 'PROGRAM MANAGER';

