-- ORDER FOR DROPPING TABLES ONE BY ONE

DROP TABLE PURCHASE_ORDER;
DROP TABLE APPROVAL_DETAILS;
DROP TABLE OUTGOING_INVOICE;
DROP TABLE PROGRAM_PART;
DROP TABLE EMPLOYEE_PROGRAM;
DROP TABLE PROGRAMS;
DROP TABLE SUPPLIER_CONTACT;
DROP TABLE SUPPLIER;
DROP TABLE PART;
DROP TABLE EMPLOYEE;
DROP TABLE CUSTOMER;
